### ISSUE TITLE
wcex/cli 启动失败

### ISSUE THREAD

**Issue by langyamu** [wc-ex/wcex#5]
- 终端里显示 success
- 启动后浏览器中报 404

![image](https://user-images.githubusercontent.com/40269393/217760175-bd735be2-2dd2-4007-abdd-5804fd7769bf.png)

![image](https://user-images.githubusercontent.com/40269393/217760311-13a3ae40-3017-400f-9d4a-bfe35b6d2ed8.png)

**Comment by zhfjyq** [comment]
404代表开发服务器已经成功启动，但未找到 index.html。
对于简单项目（非Typescript）wcex/cli 默认加载项目目录下的 /index.html。
对于TS项目，默认加载项目目录下 /src/index.html。
请检查你的项目目录中文件的位置

**Comment by langyamu** [comment]
感谢，已解决
